# Generated by Django 5.0.2 on 2024-02-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_employee_delete_user_signin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='table_client',
        ),
    ]
